---

- name: Creates directory postgresql data
  file:
    path: "{{ postgresql_data }}/{{ postgresql_version }}/main"
    owner: "postgres"
    group: "postgres"
    state: directory
    mode: 0700

- name: Sets conf file postgresql
  template:
    src: "files/postgresql.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
  notify: restart postgres
