---

- name: Install Docker
  hosts: app
  become: true
  gather_facts: true

  roles:
    - ../roles/docker

- name: Install Postgresql
  hosts: database
  become: true
  gather_facts: true

  roles:
    - ../roles/postgresql
